Repository dev-hooon/interpark, pull requests merged in 2023-12, with the labels that each got.

#12 [Feat] : 예외처리 템플릿 구현
  api/src/main/java/dev/hooon/common/exception/ApiExceptionHandler.java
  api/src/main/java/dev/hooon/common/exception/ErrorResponseTemplate.java
  core/build.gradle
  core/src/main/java/dev/hooon/common/exception/ErrorCode.java
Labels: ✏️ Feat

#13 [feat]: 엔티티 추가
  core/build.gradle
  core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
  core/src/main/java/dev/hooon/booking/domain/entity/Ticket.java
  core/src/main/java/dev/hooon/common/entity/TimeBaseEntity.java
  core/src/main/java/dev/hooon/show/domain/entity/Show.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowPeriod.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowTime.java
  core/src/main/java/dev/hooon/show/domain/entity/place/Place.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/Seat.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatGrade.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatPositionInfo.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/ShowRound.java
  core/src/main/java/dev/hooon/show/domain/entity/showlike/ShowLike.java
  core/src/main/java/dev/hooon/user/domain/entity/User.java
  core/src/main/java/dev/hooon/user/domain/entity/UserRole.java
Labels: ✏️ Feat

#15 [chore]: CICD 세팅
  .github/workflows/build-ci.yml
  .github/workflows/test-ci.yml
Labels: ⚙️ Chore

#17 [chore] : 개발 및 테스트 DB 설정 추가
  core/build.gradle
  core/src/test/java/dev/hooon/common/support/TestContainerSupport.java
  docker-compose.yml
Labels: ⚙️ Chore

#20 [hotfix] : 엔티티 수정
  api/src/test/java/dev/hooon/JacocoTest.java
  core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
  core/src/main/java/dev/hooon/booking/domain/entity/BookingStatus.java
  core/src/main/java/dev/hooon/booking/domain/entity/Ticket.java
  core/src/main/java/dev/hooon/common/entity/TimeBaseEntity.java
  core/src/main/java/dev/hooon/show/domain/entity/Show.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowCategory.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowPeriod.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowTime.java
  core/src/main/java/dev/hooon/show/domain/entity/place/Place.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/Seat.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatPositionInfo.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatStatus.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/ShowRound.java
  core/src/main/java/dev/hooon/show/domain/entity/showlike/ShowLike.java
  core/src/main/java/dev/hooon/user/domain/entity/User.java
Labels: ♻️ Hoxfix

#21 [feat] : 공연 예매 가능한 날짜, 회차 정보 조회 API 서비스 로직까지 구현
  .gitignore
  api/build.gradle
  build.gradle
  core/build.gradle
  core/src/main/java/dev/hooon/show/application/ShowService.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/ShowRound.java
  core/src/main/java/dev/hooon/show/domain/repository/SeatRepository.java
  core/src/main/java/dev/hooon/show/dto/ShowMapper.java
  core/src/main/java/dev/hooon/show/dto/query/SeatDateRoundDto.java
  core/src/main/java/dev/hooon/show/dto/response/AbleBookingDateRoundResponse.java
  core/src/main/java/dev/hooon/show/infrastructure/SeatJpaRepository.java
  core/src/test/java/dev/hooon/CoreTestApplication.java
  core/src/test/java/dev/hooon/show/application/ShowServiceTest.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/test/resources/application.yml
  core/src/test/resources/sql/seat_dummy.sql
  core/src/testFixtures/java/dev/hooon/common/support/DataJpaTestSupport.java
  core/src/testFixtures/java/dev/hooon/common/support/TestContainerSupport.java
Labels: ✏️ Feat

#23 [feat] : 공연의 예매 가능한 날짜, 회차 조회 API 구현
  api/build.gradle
  api/src/main/java/dev/hooon/show/ShowApiController.java
  api/src/test/java/dev/hooon/common/support/ApiTestSupport.java
  api/src/test/java/dev/hooon/show/ShowApiControllerTest.java
  api/src/test/resources/application.yml
  core/src/test/java/dev/hooon/common/support/DataJpaTestSupport.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/testFixtures/resources/sql/seat_dummy.sql
Labels: ✏️ Feat

#26 [refactor] : 예매 가능한 날짜, 회차 정보 조회 API 관련 테스트 리팩토링
  api/src/test/java/dev/hooon/show/ShowApiControllerTest.java
  core/src/main/java/dev/hooon/common/exception/CommonValidationError.java
  core/src/main/java/dev/hooon/show/domain/entity/Show.java
  core/src/main/java/dev/hooon/show/domain/entity/place/Place.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/Seat.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatPositionInfo.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/ShowRound.java
  core/src/main/java/dev/hooon/show/domain/repository/SeatRepository.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/test/java/dev/hooon/common/support/DataJpaTestSupport.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/testFixtures/java/dev/hooon/common/fixture/SeatFixture.java
  core/src/testFixtures/resources/sql/seat_dummy.sql
Labels: 🧚 Refactor

#28 [feat] : 예약 대기 도메인 도메인 계층 구현(엔티티, 레포지토리)
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBooking.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBookingSeat.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingStatus.java
  core/src/main/java/dev/hooon/waitingbooking/domain/repository/WaitingBookingRepository.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/adaptor/WaitingBookingRepositoryAdaptor.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/repository/WaitingBookingJpaRepository.java
Labels: ✏️ Feat

#29 feat : User 를 id 로 조회하는 서비스 로직 구현
  core/src/main/java/dev/hooon/common/exception/NotFoundException.java
  core/src/main/java/dev/hooon/user/application/UserService.java
  core/src/main/java/dev/hooon/user/domain/repository/UserRepository.java
  core/src/main/java/dev/hooon/user/exception/UserErrorCode.java
  core/src/main/java/dev/hooon/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/dev/hooon/user/infrastructure/repository/UserJpaRepository.java
Labels: ✏️ Feat

#30 [feat] : 예약 대기 도메인 도메인 계층 구현(엔티티, 레포지토리) (#28)
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBooking.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBookingSeat.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingStatus.java
  core/src/main/java/dev/hooon/waitingbooking/domain/repository/WaitingBookingRepository.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/adaptor/WaitingBookingRepositoryAdaptor.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/repository/WaitingBookingJpaRepository.java
Labels: ✏️ Feat

#33 [feat]: 공연 단건 정보 조회 API 추가
  api/src/main/java/dev/hooon/common/exception/ApiExceptionHandler.java
  api/src/main/java/dev/hooon/show/ShowDetailApiController.java
  api/src/test/java/dev/hooon/show/ShowDetailApiControllerTest.java
  core/build.gradle
  core/src/main/java/dev/hooon/show/application/ShowService.java
  core/src/main/java/dev/hooon/show/domain/entity/Show.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowPeriod.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowTime.java
  core/src/main/java/dev/hooon/show/domain/entity/place/Place.java
  core/src/main/java/dev/hooon/show/domain/repository/PlaceRepository.java
  core/src/main/java/dev/hooon/show/domain/repository/ShowRepository.java
  core/src/main/java/dev/hooon/show/dto/ShowMapper.java
  core/src/main/java/dev/hooon/show/dto/response/PlaceDetailsInfo.java
  core/src/main/java/dev/hooon/show/dto/response/ShowDetailsInfoResponse.java
  core/src/main/java/dev/hooon/show/exception/ShowErrorCode.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/PlaceRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/PlaceJpaRepository.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/ShowJpaRepository.java
  core/src/test/java/dev/hooon/show/application/ShowServiceTest.java
  core/src/test/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryAdaptorTest.java
  core/src/testFixtures/resources/sql/show_dummy.sql
Labels: ✏️ Feat

#32 feat : 예매대기 등록 API application layer 구현
  api/src/main/java/dev/hooon/common/exception/ApiExceptionHandler.java
  core/src/main/java/dev/hooon/common/exception/ValidationException.java
  core/src/main/java/dev/hooon/user/domain/entity/User.java
  core/src/main/java/dev/hooon/waitingbooking/application/WaitingBookingService.java
  core/src/main/java/dev/hooon/waitingbooking/application/facade/WaitingBookingFacade.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBooking.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBookingSeat.java
  core/src/main/java/dev/hooon/waitingbooking/dto/request/WaitingRegisterRequest.java
  core/src/main/java/dev/hooon/waitingbooking/dto/response/WaitingRegisterResponse.java
  core/src/main/java/dev/hooon/waitingbooking/exception/WaitingBookingErrorCode.java
  core/src/test/java/dev/hooon/waitingbooking/application/WaitingBookingServiceTest.java
  core/src/test/java/dev/hooon/waitingbooking/application/facade/WaitingBookingFacadeTest.java
  core/src/test/java/dev/hooon/waitingbooking/domain/entity/WaitingBookingTest.java
Labels: ✏️ Feat

#40 [feat] : 예매대기 등록 API Controller 구현
  api/src/main/java/dev/hooon/waitingbooking/WaitingBookingApiController.java
  api/src/test/java/dev/hooon/common/support/ApiTestSupport.java
  api/src/test/java/dev/hooon/waitingbooking/WaitingBookingApiControllerTest.java
  core/src/main/java/dev/hooon/waitingbooking/domain/repository/WaitingBookingRepository.java
  core/src/main/java/dev/hooon/waitingbooking/dto/request/WaitingRegisterRequest.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/adaptor/WaitingBookingRepositoryAdaptor.java
Labels: ✏️ Feat

#43 feat : 예매대기 처리 스케줄러 구현
  core/src/main/java/dev/hooon/show/application/SeatService.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatStatus.java
  core/src/main/java/dev/hooon/show/domain/repository/SeatRepository.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/main/java/dev/hooon/user/domain/entity/User.java
  core/src/main/java/dev/hooon/user/domain/repository/UserRepository.java
  core/src/main/java/dev/hooon/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/dev/hooon/waitingbooking/application/WaitingBookingService.java
  core/src/main/java/dev/hooon/waitingbooking/application/facade/WaitingBookingFacade.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBooking.java
  core/src/main/java/dev/hooon/waitingbooking/domain/repository/WaitingBookingRepository.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/adaptor/WaitingBookingRepositoryAdaptor.java
  core/src/main/java/dev/hooon/waitingbooking/infrastructure/repository/WaitingBookingJpaRepository.java
  core/src/test/java/dev/hooon/show/application/SeatServiceTest.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/test/java/dev/hooon/waitingbooking/application/facade/WaitingBookingFacadeTest.java
  core/src/test/java/dev/hooon/waitingbooking/domain/entity/WaitingBookingTest.java
  core/src/test/java/dev/hooon/waitingbooking/domain/repository/WaitingBookingRepositoryTest.java
  core/src/testFixtures/java/dev/hooon/common/fixture/SeatFixture.java
  core/src/testFixtures/java/dev/hooon/common/fixture/WaitingBookingFixture.java
  scheduler/build.gradle
  scheduler/src/main/java/dev/hooon/SchedulerApplication.java
  scheduler/src/main/java/dev/hooon/common/config/SchedulerConfig.java
  scheduler/src/main/java/dev/hooon/waitingbooking/scheduler/WaitingBookingScheduler.java
  scheduler/src/main/resources/application.yml
  scheduler/src/test/java/dev/hooon/waitingbooking/scheduler/WaitingBookingSchedulerTest.java
  settings.gradle
Labels: ✏️ Feat

#42 [feat]: 공연,날짜,회차에 대한 좌석 조회 API 추가
  api/src/main/java/dev/hooon/show/ShowSeatsApiController.java
  api/src/test/java/dev/hooon/show/ShowSeatsApiControllerTest.java
  core/src/main/java/dev/hooon/show/application/ShowSeatsService.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/Seat.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatGrade.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/ShowRound.java
  core/src/main/java/dev/hooon/show/domain/repository/SeatRepository.java
  core/src/main/java/dev/hooon/show/dto/SeatMapper.java
  core/src/main/java/dev/hooon/show/dto/query/seats/SeatsDetailDto.java
  core/src/main/java/dev/hooon/show/dto/query/seats/SeatsInfoDto.java
  core/src/main/java/dev/hooon/show/dto/query/seats/ShowSeatsDto.java
  core/src/main/java/dev/hooon/show/dto/response/seats/SeatsDetailResponse.java
  core/src/main/java/dev/hooon/show/dto/response/seats/SeatsInfoResponse.java
  core/src/main/java/dev/hooon/show/dto/response/seats/ShowSeatsResponse.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/test/java/dev/hooon/show/application/ShowSeatsServiceTest.java
  core/src/test/java/dev/hooon/show/application/ShowServiceTest.java
  core/src/test/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryAdaptorTest.java
  core/src/test/java/dev/hooon/show/infrastructure/repository/SeatJpaRepositoryTest.java
  core/src/testFixtures/java/dev/hooon/common/fixture/TestFixture.java
  core/src/testFixtures/resources/sql/show_seats_dummy.sql
Labels: ✏️ Feat
