Repository dev-hooon/interpark, pull requests merged in 2024-01, with the labels that each got.

#41 [feat] : 회원가입 api 구현 & use 엔티티 추가 구현
  api/src/main/java/dev/hooon/user/UserApiController.java
  api/src/test/java/dev/hooon/user/UserApiControllerTest.java
  core/build.gradle
  core/src/main/java/dev/hooon/auth/entity/BcryptImpl.java
  core/src/main/java/dev/hooon/auth/entity/EncryptHelper.java
  core/src/main/java/dev/hooon/user/application/UserService.java
  core/src/main/java/dev/hooon/user/domain/entity/User.java
  core/src/main/java/dev/hooon/user/domain/repository/UserRepository.java
  core/src/main/java/dev/hooon/user/dto/UserMapper.java
  core/src/main/java/dev/hooon/user/dto/request/UserJoinRequest.java
  core/src/main/java/dev/hooon/user/dto/response/UserJoinResponse.java
  core/src/main/java/dev/hooon/user/exception/UserErrorCode.java
  core/src/main/java/dev/hooon/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/dev/hooon/user/infrastructure/repository/UserJpaRepository.java
  core/src/test/java/dev/hooon/user/application/UserServiceTest.java
  core/src/test/java/dev/hooon/user/domain/entity/UserTest.java
Labels: ✏️ Feat, ✅ Test

#51 [chore]: test CI 수정
  .github/workflows/test-ci.yml
  build.gradle
Labels: ⚙️ Chore

#52 [chore] : 스케줄러에 shedlock 설정 추가 및 적용
  .gitignore
  api/src/main/java/dev/hooon/ApiApplication.java
  core/build.gradle
  core/src/main/java/dev/hooon/common/config/RedisConfig.java
  scheduler/build.gradle
  scheduler/src/main/java/dev/hooon/SchedulerApplication.java
  scheduler/src/main/java/dev/hooon/common/config/SchedulerConfig.java
  scheduler/src/main/java/dev/hooon/waitingbooking/scheduler/WaitingBookingScheduler.java
Labels: ⚙️ Chore

#53 [feat] : 회원가입 api 구현 & user 엔티티 추가 구현
  api/src/main/java/dev/hooon/user/UserApiController.java
  api/src/test/java/dev/hooon/user/UserApiControllerTest.java
  core/build.gradle
  core/src/main/java/dev/hooon/auth/entity/BcryptImpl.java
  core/src/main/java/dev/hooon/auth/entity/EncryptHelper.java
  core/src/main/java/dev/hooon/user/application/UserService.java
  core/src/main/java/dev/hooon/user/domain/entity/User.java
  core/src/main/java/dev/hooon/user/domain/repository/UserRepository.java
  core/src/main/java/dev/hooon/user/dto/UserMapper.java
  core/src/main/java/dev/hooon/user/dto/request/UserJoinRequest.java
  core/src/main/java/dev/hooon/user/dto/response/UserJoinResponse.java
  core/src/main/java/dev/hooon/user/exception/UserErrorCode.java
  core/src/main/java/dev/hooon/user/infrastructure/adaptor/UserRepositoryAdaptor.java
  core/src/main/java/dev/hooon/user/infrastructure/repository/UserJpaRepository.java
  core/src/test/java/dev/hooon/user/application/UserServiceTest.java
  core/src/test/java/dev/hooon/user/domain/entity/UserTest.java
  core/src/test/java/dev/hooon/waitingbooking/domain/repository/WaitingBookingRepositoryTest.java
  scheduler/src/test/java/dev/hooon/waitingbooking/scheduler/WaitingBookingSchedulerTest.java
Labels: ✏️ Feat

#57 feat : Jpa Auditing 설정 추가
  core/src/main/java/dev/hooon/common/config/AuditingConfig.java
Labels: ✏️ Feat

#56 [feat]: 공연 예매 API 추가
  api/src/main/java/dev/hooon/ticketbooking/TicketBookingApiController.java
  api/src/main/java/dev/hooon/waitingbooking/WaitingBookingApiController.java
  api/src/test/java/dev/hooon/ticketbooking/TicketBookingApiControllerTest.java
  core/src/main/java/dev/hooon/booking/application/BookingService.java
  core/src/main/java/dev/hooon/booking/application/fascade/TicketBookingFacade.java
  core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
  core/src/main/java/dev/hooon/booking/domain/entity/Ticket.java
  core/src/main/java/dev/hooon/booking/domain/repository/BookingRepository.java
  core/src/main/java/dev/hooon/booking/dto/BookingMapper.java
  core/src/main/java/dev/hooon/booking/dto/request/TicketBookingRequest.java
  core/src/main/java/dev/hooon/booking/dto/response/TicketBookingResponse.java
  core/src/main/java/dev/hooon/booking/dto/response/TicketResponse.java
  core/src/main/java/dev/hooon/booking/exception/BookingErrorCode.java
  core/src/main/java/dev/hooon/booking/infrastructure/adaptor/BookingRepositoryAdaptor.java
  core/src/main/java/dev/hooon/booking/infrastructure/repository/BookingJpaRepository.java
  core/src/main/java/dev/hooon/show/application/SeatService.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/Seat.java
  core/src/main/java/dev/hooon/show/domain/entity/seat/SeatPositionInfo.java
  core/src/main/java/dev/hooon/show/domain/repository/SeatRepository.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/test/java/dev/hooon/booking/application/fascade/TicketBookingFacadeIntegrationTest.java
  core/src/test/java/dev/hooon/booking/application/fascade/TicketBookingFacadeTest.java
  core/src/test/java/dev/hooon/show/domain/entity/seat/SeatTest.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/testFixtures/java/dev/hooon/common/fixture/SeatFixture.java
  core/src/testFixtures/java/dev/hooon/common/fixture/TestFixture.java
  core/src/testFixtures/resources/sql/booking_dummy.sql
Labels: ✏️ Feat

#60 feat : 공연 랭킹기능 구현
  api/src/main/java/dev/hooon/show/RankingApiController.java
  api/src/test/java/dev/hooon/JacocoTest.java
  api/src/test/java/dev/hooon/show/RankingApiControllerTest.java
  api/src/test/java/dev/hooon/user/UserApiControllerTest.java
  core/build.gradle
  core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
  core/src/main/java/dev/hooon/common/config/RedisConfig.java
  core/src/main/java/dev/hooon/show/application/PeriodType.java
  core/src/main/java/dev/hooon/show/application/RankingService.java
  core/src/main/java/dev/hooon/show/application/facade/RankingCacheFacade.java
  core/src/main/java/dev/hooon/show/domain/entity/ShowCategory.java
  core/src/main/java/dev/hooon/show/domain/repository/ShowRepository.java
  core/src/main/java/dev/hooon/show/dto/ShowMapper.java
  core/src/main/java/dev/hooon/show/dto/query/ShowStatisticDto.java
  core/src/main/java/dev/hooon/show/dto/request/RankingRequest.java
  core/src/main/java/dev/hooon/show/dto/response/AbleBookingDateRoundResponse.java
  core/src/main/java/dev/hooon/show/dto/response/RankingResponse.java
  core/src/main/java/dev/hooon/show/exception/ShowErrorCode.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/ShowJpaRepository.java
  core/src/test/java/dev/hooon/common/config/TestAuditingConfig.java
  core/src/test/java/dev/hooon/common/support/DataJpaTestSupport.java
  core/src/test/java/dev/hooon/show/application/PeriodTypeTest.java
  core/src/test/java/dev/hooon/show/application/RankingServiceTest.java
  core/src/test/java/dev/hooon/show/application/facade/RankingCacheFacadeTest.java
  core/src/test/java/dev/hooon/show/domain/entity/ShowCategoryTest.java
  core/src/test/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryAdaptorTest.java
  core/src/test/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryTest.java
  core/src/testFixtures/java/dev/hooon/common/fixture/SeatFixture.java
  core/src/testFixtures/java/dev/hooon/common/fixture/TestFixture.java
  core/src/testFixtures/java/dev/hooon/common/fixture/UserFixture.java
  core/src/testFixtures/java/dev/hooon/common/support/IntegrationTestSupport.java
  core/src/testFixtures/resources/sql/show_dummy.sql
  scheduler/src/main/java/dev/hooon/show/scheduler/RankingScheduler.java
  scheduler/src/test/java/dev/hooon/show/scheduler/RankingSchedulerTest.java
  scheduler/src/test/java/dev/hooon/waitingbooking/scheduler/WaitingBookingSchedulerTest.java
Labels: ✏️ Feat

#63 [feat] : 예매된 좌석 조회 API 구현
  api/src/main/java/dev/hooon/show/ShowSeatsApiController.java
  api/src/test/java/dev/hooon/show/ShowSeatsApiControllerTest.java
  core/src/main/java/dev/hooon/common/config/TimeConfig.java
  core/src/main/java/dev/hooon/show/application/PeriodType.java
  core/src/main/java/dev/hooon/show/application/RankingService.java
  core/src/main/java/dev/hooon/show/application/SeatService.java
  core/src/main/java/dev/hooon/show/domain/repository/SeatRepository.java
  core/src/main/java/dev/hooon/show/dto/SeatMapper.java
  core/src/main/java/dev/hooon/show/dto/request/BookedSeatQueryRequest.java
  core/src/main/java/dev/hooon/show/dto/response/ShowSeatResponse.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/main/java/dev/hooon/waitingbooking/application/facade/WaitingBookingFacade.java
  core/src/test/java/dev/hooon/booking/infrastructure/repository/BookingJpaRepositoryTest.java
  core/src/test/java/dev/hooon/show/application/PeriodTypeTest.java
  core/src/test/java/dev/hooon/show/application/RankingServiceTest.java
  core/src/test/java/dev/hooon/show/application/SeatServiceTest.java
  core/src/test/java/dev/hooon/show/application/facade/RankingCacheFacadeTest.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/test/java/dev/hooon/waitingbooking/application/facade/WaitingBookingFacadeTest.java
  core/src/testFixtures/java/dev/hooon/common/support/IntegrationTestSupport.java
  core/src/testFixtures/resources/sql/show_seats_dummy.sql
  scheduler/src/main/java/dev/hooon/waitingbooking/scheduler/WaitingBookingScheduler.java
  scheduler/src/test/java/dev/hooon/show/scheduler/RankingSchedulerTest.java
  scheduler/src/test/java/dev/hooon/waitingbooking/scheduler/WaitingBookingSchedulerTest.java
Labels: ✏️ Feat

#67 [chore] : 스웨거 설정 추가 및 적용
  api/build.gradle
  api/src/main/java/dev/hooon/auth/AuthApiController.java
  api/src/main/java/dev/hooon/bookingcancel/BookingCancelApiController.java
  api/src/main/java/dev/hooon/common/config/SwaggerConfig.java
  api/src/main/java/dev/hooon/common/config/WebConfig.java
  api/src/main/java/dev/hooon/show/RankingApiController.java
  api/src/main/java/dev/hooon/show/ShowApiController.java
  api/src/main/java/dev/hooon/show/ShowDetailApiController.java
  api/src/main/java/dev/hooon/show/ShowSeatsApiController.java
  api/src/main/java/dev/hooon/ticketbooking/TicketBookingApiController.java
  api/src/main/java/dev/hooon/user/UserApiController.java
  api/src/main/java/dev/hooon/waitingbooking/WaitingBookingApiController.java
  scheduler/src/test/java/dev/hooon/waitingbooking/scheduler/WaitingBookingSchedulerTest.java
Labels: ⚙️ Chore

#70 [refactor] : 인증필요한 API 에 인증 적용 + 스케줄러 테스트 간헐적으로 터지는 버그 해
  api/src/main/java/dev/hooon/bookingcancel/BookingCancelApiController.java
  api/src/main/java/dev/hooon/ticketbooking/TicketBookingApiController.java
  api/src/main/java/dev/hooon/waitingbooking/WaitingBookingApiController.java
  api/src/test/java/dev/hooon/auth/AuthApiControllerTest.java
  api/src/test/java/dev/hooon/bookingcancel/BookingCancelApiControllerTest.java
  api/src/test/java/dev/hooon/common/support/ApiTestSupport.java
  api/src/test/java/dev/hooon/show/RankingApiControllerTest.java
  api/src/test/java/dev/hooon/show/ShowApiControllerTest.java
  api/src/test/java/dev/hooon/show/ShowDetailApiControllerTest.java
  api/src/test/java/dev/hooon/show/ShowSeatsApiControllerTest.java
  api/src/test/java/dev/hooon/ticketbooking/TicketBookingApiControllerTest.java
  api/src/test/java/dev/hooon/user/UserApiControllerTest.java
  api/src/test/java/dev/hooon/waitingbooking/WaitingBookingApiControllerTest.java
  api/src/test/resources/application.yml
  core/src/test/resources/application.yml
  scheduler/src/main/java/dev/hooon/common/config/SchedulerConfig.java
  scheduler/src/main/java/dev/hooon/common/config/ShedLockConfig.java
  scheduler/src/test/java/dev/hooon/common/support/SchedulerTestSupport.java
  scheduler/src/test/java/dev/hooon/show/scheduler/RankingSchedulerTest.java
  scheduler/src/test/java/dev/hooon/waitingbooking/scheduler/WaitingBookingSchedulerTest.java
  scheduler/src/test/resources/application.yml
Labels: 🧚 Refactor

#69 [feat] : 사용자는 카테고리별로 전체 공연의 정보를 조회할 수 있다
  api/src/main/java/dev/hooon/show/ShowsApiController.java
  api/src/test/java/dev/hooon/show/ShowsApiControllerTest.java
  core/src/main/java/dev/hooon/auth/application/JwtProvider.java
  core/src/main/java/dev/hooon/auth/infrastructure/adaptor/AuthRepositoryAdaptor.java
  core/src/main/java/dev/hooon/common/dto/PagedResponse.java
  core/src/main/java/dev/hooon/show/application/ShowService.java
  core/src/main/java/dev/hooon/show/domain/repository/ShowRepository.java
  core/src/main/java/dev/hooon/show/dto/ShowMapper.java
  core/src/main/java/dev/hooon/show/dto/response/ShowInfoResponse.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/ShowJpaRepository.java
  core/src/test/java/dev/hooon/auth/application/JwtProviderTest.java
Labels: ✏️ Feat, ✅ Test

#62 [feat]: 조회 기간에 따른 예매 티켓 조회 API 추가
  api/build.gradle
  api/src/main/java/dev/hooon/booking/BookingApiController.java
  api/src/test/java/dev/hooon/booking/BookingApiControllerTest.java
  core/src/main/java/dev/hooon/booking/application/BookingService.java
  core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
  core/src/main/java/dev/hooon/booking/domain/entity/Ticket.java
  core/src/main/java/dev/hooon/booking/domain/repository/BookingRepository.java
  core/src/main/java/dev/hooon/booking/dto/BookingMapper.java
  core/src/main/java/dev/hooon/booking/dto/response/BookingListResponse.java
  core/src/main/java/dev/hooon/booking/dto/response/BookingResponse.java
  core/src/main/java/dev/hooon/booking/dto/response/ShowInfoResponse.java
  core/src/main/java/dev/hooon/booking/infrastructure/adaptor/BookingRepositoryAdaptor.java
  core/src/main/java/dev/hooon/booking/infrastructure/repository/BookingJpaRepository.java
  core/src/testFixtures/resources/sql/user_bookings_find.sql
Labels: ✏️ Feat

#75 [refactor] : 기존 비관적락 방식의 예매를 Redis 를 활용한(분산락X) 동시성 제어 방식으로 마이그레이션
  api/build.gradle
  api/src/main/java/dev/hooon/ticketbooking/TicketBookingApiController.java
  api/src/test/java/dev/hooon/bookingcancel/BookingCancelApiControllerTest.java
  api/src/test/java/dev/hooon/common/support/ApiTestSupport.java
  api/src/test/java/dev/hooon/show/RankingApiControllerTest.java
  core/src/main/java/dev/hooon/booking/aop/BookingConcurrency.java
  core/src/main/java/dev/hooon/booking/aop/BookingConcurrencyHandlerAspect.java
  core/src/main/java/dev/hooon/booking/application/fascade/TicketBookingFacade.java
  core/src/main/java/dev/hooon/booking/domain/entity/Booking.java
  core/src/main/java/dev/hooon/booking/domain/entity/Ticket.java
  core/src/main/java/dev/hooon/common/config/AopConfig.java
  core/src/main/java/dev/hooon/show/application/SeatService.java
  core/src/main/java/dev/hooon/show/infrastructure/adaptor/SeatRepositoryAdaptor.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/test/java/dev/hooon/booking/application/BookingServiceTest.java
  core/src/test/java/dev/hooon/booking/application/fascade/TicketBookingFacadeIntegrationTest.java
  core/src/test/java/dev/hooon/booking/application/fascade/TicketBookingFacadeTest.java
  core/src/test/java/dev/hooon/booking/infrastructure/repository/BookingJpaRepositoryTest.java
  core/src/test/java/dev/hooon/show/domain/repository/SeatRepositoryTest.java
  core/src/test/java/dev/hooon/show/infrastructure/adaptor/ShowRepositoryTest.java
  core/src/test/java/dev/hooon/waitingbooking/application/WaitingBookingServiceTest.java
  core/src/testFixtures/java/dev/hooon/common/support/IntegrationTestSupport.java
  scheduler/src/main/java/dev/hooon/common/config/SchedulerConfig.java
  scheduler/src/test/java/dev/hooon/common/support/SchedulerTestSupport.java
  scheduler/src/test/java/dev/hooon/show/scheduler/RankingSchedulerTest.java
Labels: 🧚 Refactor

#74 [refactor]: 패키지 정리 및 리팩토링
  api/src/main/java/dev/hooon/booking/BookingApiController.java
  api/src/main/java/dev/hooon/bookingcancel/BookingCancelApiController.java
  api/src/main/java/dev/hooon/ticketbooking/TicketBookingApiController.java
  api/src/test/java/dev/hooon/booking/BookingCancelApiControllerTest.java
  api/src/test/java/dev/hooon/booking/TicketBookingApiControllerTest.java
Labels: 🧚 Refactor

#76 [refactor] : PostgreSQL -> MySQL 마이그레이션
  api/src/test/java/dev/hooon/show/ShowSeatsApiControllerTest.java
  api/src/test/resources/application.yml
  core/build.gradle
  core/src/main/java/dev/hooon/show/infrastructure/repository/SeatJpaRepository.java
  core/src/main/java/dev/hooon/show/infrastructure/repository/ShowJpaRepository.java
  core/src/main/java/dev/hooon/waitingbooking/domain/entity/WaitingBooking.java
  core/src/test/java/dev/hooon/show/infrastructure/repository/SeatJpaRepositoryTest.java
  core/src/test/resources/application.yml
  core/src/testFixtures/java/dev/hooon/common/support/TestContainerSupport.java
  docker-compose.yml
  scheduler/src/test/resources/application.yml
Labels: 🧚 Refactor
